# -*- coding: utf-8 -*-
"""CE4041_Project_2_AdaBoost_Classifier (2).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKOiHecnZNKSndFFrV_RWFUuktr8Cukw

#CE4041 Project 2: AdaBoost Classifier using "Weighted Weak Linear" Base Classifiers

##Problem Statement:
Develop a binary ("bipolar-binary", {-1/+1}) encoded AdaBoost classifier with a single output, returning +1 for "in class 1" and -1 for "in class 2".  The AdaBoost classifier is to use "weighted weak linear classifiers" as its base learners.  
Write code for the weak learner, for the AdaBoost training regime, and to plot the data points and the decision boundary used by your AdaBoost classifier.

You should also write code to plot the classification accuracy (on the testing set) of the AdaBoost strong classifier as the number of base learners in it is increased from 1 to n, where n is the number of base learners employed in your system. You have to decide on an appropriate value of n, and justify your choice.

How many base classifiers are needed to achieve 100% classification accuracy on the training set (n)?  What is the maximum accuracy achievable on the testing set? Can the testing set get to 100% classification accuracy?  How many weak learners give maximum accuracy on the testing set (ntest)?
"""



"""##Submitted By:
1. Aakanksha Rawat - 25243829
2. Asghar Aga Murthuza - 25210645
3. Bhagyalakshmy Saburaj - 25275224
4. Rosanne Josephin Fernando - 25275216
5. Roshni Ravi - 25015168
"""

# Import necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import os
from sklearn.metrics import accuracy_score

# --- 1. Weighted Weak Linear Classifier Class ---
class WeightedWeakLinearClassifier:
    """
    A weak learner inspired by linear separation based on weighted class means,
    optimally selecting the threshold for minimal weighted error (stump approach).
    """
    def __init__(self):
        self.orientation_vector = None
        self.threshold = None
        self.polarity = 1

    def fit(self, X, y, sample_weights):
        """Trains the weak classifier by finding the optimal hyperplane."""

        positive_class_indices = (y == 1)
        negative_class_indices = (y == -1)

        positive_class = X[positive_class_indices]
        negative_class = X[negative_class_indices]
        positive_weights = sample_weights[positive_class_indices]
        negative_weights = sample_weights[negative_class_indices]

        # --- Robust Weighted Mean Calculation ---
        w_pos_sum = np.sum(positive_weights)
        w_neg_sum = np.sum(negative_weights)

        # Compute weighted class means (Fall back to unweighted if sum of weights is near zero)
        if w_pos_sum > 1e-10 and len(positive_class) > 0:
            mean_positive = np.average(positive_class, axis=0, weights=positive_weights)
        elif len(positive_class) > 0:
            mean_positive = np.mean(positive_class, axis=0)
        else:
             mean_positive = np.zeros(X.shape[1])

        if w_neg_sum > 1e-10 and len(negative_class) > 0:
            mean_negative = np.average(negative_class, axis=0, weights=negative_weights)
        elif len(negative_class) > 0:
            mean_negative = np.mean(negative_class, axis=0)
        else:
             mean_negative = np.zeros(X.shape[1])

        # Orientation vector (p)
        orientation = mean_positive - mean_negative
        norm = np.linalg.norm(orientation)

        # Normalise the orientation vector (p)
        if norm > 1e-10:
            self.orientation_vector = orientation / norm
        else:
            # If means coincide, choose an arbitrary direction (e.g., first axis)
            self.orientation_vector = np.array([1.0] + [0.0] * (X.shape[1] - 1))

        # Project all points onto the orientation vector
        projected_data = X @ self.orientation_vector

        # --- Robust Threshold Search (1D Stump) ---
        minimum_error = float('inf')
        best_threshold = None
        best_polarity = 1

        unique_projections = np.unique(projected_data)
        candidate_thresholds = []
        if len(unique_projections) > 1:
            # Midpoints between unique projected points
            candidate_thresholds.extend((unique_projections[:-1] + unique_projections[1:]) / 2)

        # Add extreme points for boundary checks
        candidate_thresholds.append(unique_projections[0] - 1.0)
        candidate_thresholds.append(unique_projections[-1] + 1.0)

        candidate_thresholds = np.unique(candidate_thresholds)

        for threshold in candidate_thresholds:
            for polarity in [1, -1]:
                # Polarity 1: If projection >= threshold, predict 1, else -1
                if polarity == 1:
                    predictions = np.where(projected_data >= threshold, 1, -1)
                # Polarity -1: If projection < threshold, predict 1, else -1
                else:
                    predictions = np.where(projected_data < threshold, 1, -1)

                # Weighted misclassification error
                error = np.sum(sample_weights[predictions != y])

                if error < minimum_error:
                    minimum_error = error
                    best_threshold = threshold
                    best_polarity = polarity

        self.threshold = best_threshold
        self.polarity = best_polarity
        return minimum_error

    def predict(self, X):
        """Makes predictions for a given set of features."""
        if self.orientation_vector is None or self.threshold is None:
             # Should only happen if the weak learner was not successfully fitted
             return np.zeros(X.shape[0])

        projected_data = X @ self.orientation_vector

        if self.polarity == 1:
            # Class +1 if projected_data >= threshold
            return np.where(projected_data >= self.threshold, 1, -1)
        else:
            # Class +1 if projected_data < threshold
            return np.where(projected_data < self.threshold, 1, -1)

class AdaBoost:
    """Implements the AdaBoost algorithm using custom weak learners."""
    def __init__(self, num_learners,early_stopping=False, tol=1.0):
        self.num_learners = num_learners
        self.weak_learners = []
        self.learner_weights = []
        self.errors_history = []
        self.sample_weights_history = []
        self.early_stopping = early_stopping
        self.tol = tol

    def fit(self, features, labels):
        num_samples = features.shape[0]
        self.weak_learners = []
        self.learner_weights = []
        self.errors_history = []
        self.sample_weights_history = []

        # Initialise uniform sample weights
        sample_weights = np.ones(num_samples) / num_samples

        for i in range(self.num_learners):
            weak_learner = WeightedWeakLinearClassifier()
            error = weak_learner.fit(features, labels, sample_weights)

            # Store the error before checks
            self.errors_history.append(error)

            # --- Early Stopping Checks ---
            if error < 1e-10:
                print(f"Perfect classification (error=0) achieved at iteration {i+1}.")
                learner_weight = 0.5 * np.log((1 - 1e-10) / 1e-10)
                self.weak_learners.append(weak_learner)
                self.learner_weights.append(learner_weight)
                self.sample_weights_history.append(sample_weights.copy())
                self.num_learners = i + 1
                break
            elif error >= 0.5:
                print(f"Weak learner error >= 0.5 at iteration {i+1}. Stopping.")
                self.num_learners = i
                break

            # Compute learner weight (alpha_t)
            learner_weight = 0.5 * np.log((1 - error) / error)
            predictions = weak_learner.predict(features)

            # Store sample weights *before* update (weights used for this iteration)
            self.sample_weights_history.append(sample_weights.copy())

            # Weight update rule
            sample_weights *= np.exp(-learner_weight * labels * predictions)
            sample_weights /= np.sum(sample_weights)  # Normalize

            self.weak_learners.append(weak_learner)
            self.learner_weights.append(learner_weight)
            if self.early_stopping:
              # Compute strong classifier prediction so far
              current_pred = self.predict(features)
              accuracy = np.mean(current_pred == labels)
              print(f"Iteration {i+1}, training accuracy: {accuracy*100:.2f}%")
            # Check 100% training accuracy to determine final 'n'
            if np.mean(self.predict(features) == labels) == 1.0:
                print(f"100% training accuracy achieved at iteration {i+1}")
                self.num_learners = i + 1
                break

        self.num_learners = len(self.weak_learners)

    def predict(self, features):
        """Strong classifier prediction: H(x) = sign(sum(alpha_t * h_t(x)))"""
        if not self.weak_learners:
             return np.zeros(features.shape[0])

        final_prediction = np.zeros(features.shape[0])
        for learner, weight in zip(self.weak_learners, self.learner_weights):
            final_prediction += weight * learner.predict(features)
        return np.sign(final_prediction)

    def staged_predict(self, features):
      """Returns a list of predictions after each learner is added."""
      cumulative_prediction = np.zeros(features.shape[0])
      predictions_list = []
      for alpha, learner in zip(self.learner_weights, self.weak_learners):
        cumulative_prediction += alpha * learner.predict(features)
        predictions_list.append(np.sign(cumulative_prediction.copy()))
      return predictions_list

# --- Utility Functions for Data Loading and Plotting ---
def load_data(filename):
    """Loads the features (X) and labels (y) from a text file."""
    if not os.path.exists(filename):
        print(f"Error: File not found: {filename}")
        return np.array([]), np.array([])

    data = np.loadtxt(filename)
    X = data[:, :-1]  # Features
    y = data[:, -1]   # Labels
    return X, y

def plot_decision_boundary(X, y, model, title, steps=200, cmap='cividis'):
    """Plots the decision boundary of the strong classifier."""
    if not model.weak_learners: return

    cmap = plt.get_cmap(cmap)
    xmin, xmax = X[:, 0].min() - 1, X[:, 0].max() + 1
    ymin, ymax = X[:, 1].min() - 1, X[:, 1].max() + 1
    x_span = np.linspace(xmin, xmax, steps)
    y_span = np.linspace(ymin, ymax, steps)
    xx, yy = np.meshgrid(x_span, y_span)

    grid_points = np.c_[xx.ravel(), yy.ravel()]
    labels = model.predict(grid_points)
    z = labels.reshape(xx.shape)

    fig, ax = plt.subplots(figsize=(8, 6))

    # Plot contour
    ax.contourf(xx, yy, z, levels=[-1.1, 0, 1.1], colors=['#F8B6B6', '#A6CCF5'], alpha=0.6)
    ax.contour(xx, yy, z, levels=[0], colors='k', linewidths=2)

    # Plot data points
    scatter = ax.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap, edgecolors='k', linewidths=0.5, s=50)
    handles, default_labels = scatter.legend_elements()
    custom_labels = ['Class -1', 'Class +1']
    legend1 = ax.legend(handles,
                        custom_labels,
                        loc="upper right",
                        title="Classes")

    ax.add_artist(legend1)

    ax.set_title(title)
    ax.set_xlabel('Feature 1 ($x_1$)')
    ax.set_ylabel('Feature 2 ($x_2$)')
    ax.grid(True, linestyle='--', alpha=0.6)
    plt.tight_layout()
    plt.show()

def plot_accuracy_vs_learners(accuracies_train, accuracies_test, n_learners, n_test):
    """Plots the training and testing accuracy vs. the number of base learners."""
    fig, ax = plt.subplots(figsize=(9, 6))

    ax.plot(range(1, n_learners + 1), accuracies_train, label='Training Accuracy', color='blue', marker='o', markersize=3)
    ax.plot(range(1, n_learners + 1), accuracies_test, label='Testing Accuracy', color='red', marker='x', markersize=3)

    max_test_acc = np.max(accuracies_test)

    # Annotate max test accuracy point
    ax.axvline(x=n_test, color='red', linestyle='--', alpha=0.7, label=f'Max Test Acc at $n_{{test}}={n_test}$')

    ax.annotate(f'Max Test Acc: {max_test_acc:.4f}',
                xy=(n_test, max_test_acc),
                xytext=(n_test + 5, max_test_acc - 0.05),
                arrowprops=dict(facecolor='black', shrink=0.05, width=1, headwidth=5),
                horizontalalignment='left')

    ax.set_xlabel('Number of Weak Learners ($t$)')
    ax.set_ylabel('Classification Accuracy')
    ax.set_title('AdaBoost Strong Classifier Accuracy vs. Number of Weak Learners')
    ax.legend()
    ax.grid(True, linestyle='--')
    plt.tight_layout()
    plt.show()

def plot_weak_learner_errors(errors_list, n_learners, title=r"Weak Learner Errors ($\epsilon_t$) Over Iterations"): # Line 73
    """
    Plots the weighted misclassification error (epsilon_t) for each weak learner.
    """
    fig, ax = plt.subplots(figsize=(9, 6))
    # Note the 'r' prefix here:
    ax.plot(range(1, n_learners + 1), errors_list, label=r'Weighted Error ($\epsilon_t$)', color='purple', marker='o', markersize=3) # Line 78
    ax.axhline(y=0.5, color='r', linestyle='--', label='Random Guessing (Error = 0.5)')

    ax.set_xlabel('Weak Learner Iteration ($t$)')
    # Note the 'r' prefix here:
    ax.set_ylabel(r'Weighted Misclassification Error ($\epsilon_t$)') # Line 82
    ax.set_title(title)
    ax.legend()
    ax.grid(True, linestyle='--')
    plt.tight_layout()
    plt.show()

def plot_weak_learner_boundary_and_weights(X, y, learner, iteration, sample_weights, cmap='Paired'):
    """
    Plots the decision boundary of a single weak learner with data point sizes
    proportional to their sample weights.
    """
    if learner.orientation_vector is None or learner.threshold is None: return

    cmap_obj = plt.get_cmap(cmap)
    xmin, xmax = X[:, 0].min() - 1, X[:, 0].max() + 1
    ymin, ymax = X[:, 1].min() - 1, X[:, 1].max() + 1

    # Create a mesh to plot decision boundary
    xx, yy = np.meshgrid(np.linspace(xmin, xmax, 100), np.linspace(ymin, ymax, 100))
    Z = learner.predict(np.c_[xx.ravel(), yy.ravel()]).reshape(xx.shape)

    fig, ax = plt.subplots(figsize=(8, 6))

    # Plot the decision region contour
    ax.contourf(xx, yy, Z, levels=[-1.1, 0, 1.1], colors=['#F8B6B6', '#A6CCF5'], alpha=0.6)
    ax.contour(xx, yy, Z, levels=[0], colors='k', linewidths=1.5)

    # Plot data points, with size proportional to sample weights
    if np.max(sample_weights) > 0:
        s_sizes = 10 + 190 * (sample_weights / np.max(sample_weights))
    else:
        s_sizes = 50 * np.ones_like(sample_weights)

    scatter = ax.scatter(X[:, 0], X[:, 1], c=y, cmap=cmap_obj, edgecolors='k', s=s_sizes, linewidths=0.5)

    # Plot the linear separating line
    if np.abs(learner.orientation_vector[1]) > 1e-10:
        x_plot = np.array([xmin, xmax])
        # Line equation: y = (-p_x/p_y) * x + (threshold/p_y)
        y_plot = (-learner.orientation_vector[0] / learner.orientation_vector[1]) * x_plot + \
                 (learner.threshold / learner.orientation_vector[1])
        ax.plot(x_plot, y_plot, 'k--', linewidth=2, label='Weak Learner Boundary')
    elif np.abs(learner.orientation_vector[0]) > 1e-10:
        # Vertical line
        ax.axvline(x=learner.threshold / learner.orientation_vector[0], color='k', linestyle='--', linewidth=2, label='Weak Learner Boundary')

    ax.set_title(f"Weak Learner {iteration+1} Boundary (Weights for Iteration {iteration+1})")
    ax.set_xlabel('Feature 1 ($x_1$)')
    ax.set_ylabel('Feature 2 ($x_2$)')
    ax.grid(True, linestyle='--', alpha=0.6)
    ax.legend(handles=scatter.legend_elements()[0], labels=['Class -1', 'Class +1']) # Simplified legend
    plt.tight_layout()
    plt.show()

# Load Data
X_train, y_train = load_data('adaboost-train-24.txt')
X_test, y_test = load_data('adaboost-test-24.txt')

if X_train.size == 0 or X_test.size == 0:
    print("Cannot run analysis due to missing data files.")
else:
    # Set maximum learners and let the 100% accuracy condition find 'n'
    MAX_LEARNERS = 150

    print(f"--- Starting AdaBoost Training with max {MAX_LEARNERS} learners ---")
    adaboost = AdaBoost(num_learners=MAX_LEARNERS, early_stopping=True, tol=1.0)
    adaboost.fit(X_train, y_train)
    n = adaboost.num_learners

    print(f"\n--- Training Complete (Used n={n} learners) ---")

# --- Performance Evaluation ---
y_stage_pred_train_list = adaboost.staged_predict(X_train)
accuracies_train = [np.mean(y_stage_pred == y_train) for y_stage_pred in y_stage_pred_train_list]

y_stage_pred_test_list = adaboost.staged_predict(X_test)
accuracies_test = [np.mean(y_stage_pred == y_test) for y_stage_pred in y_stage_pred_test_list]

# Find n_test (Learners for Max Test Accuracy)
max_test_acc = np.max(accuracies_test)
n_test = np.argmax(accuracies_test) + 1

# Final Summary
print("\n--- Summary of Results for Report ---")
print(f"1. Learners for 100% Training Acc (n): {n}")
print(f"2. Maximum Accuracy on Testing Set: {max_test_acc*100:.4f}%")
print(f"3. Can Testing Set get to 100%? {'No' if max_test_acc < 1.0 else 'Yes'}")
print(f"4. The optimal number of weak learners to achieve the highest classification accuracy(n_test): {n_test}")

# --- Required Plots ---

print("\n--- Generating Required Plots (Accuracy and Boundary) ---")
plot_accuracy_vs_learners(accuracies_train, accuracies_test, n, n_test)
plot_decision_boundary(X_train, y_train, adaboost,
                           title=f"AdaBoost Decision Boundary (Strong Classifier with n={n} Learners)")

# --- Additional Visualizations ---

print("\n--- Generating Additional Visualizations (Error and Weak Learners) ---")

    # Plot errors of weak learners
if adaboost.errors_history:
  plot_weak_learner_errors(adaboost.errors_history, n)

# Plot selected weak learner boundaries and sample weights at key iterations
plot_indices = []

# 1. First learner (t=1)
plot_indices.append(0)
# 2. Learner at max test accuracy (n_test)
if n_test > 0 and n_test <= n:
   plot_indices.append(n_test - 1)
# 3. Final learner (t=n)
if n > 1 and n - 1 != plot_indices[-1]:
  plot_indices.append(n - 1)

unique_plot_indices = sorted(list(set(plot_indices)))

for idx in unique_plot_indices:
  if idx < len(adaboost.weak_learners):
    current_learner = adaboost.weak_learners[idx]
    current_weights = adaboost.sample_weights_history[idx] # Weights at the start of this iteration

      # Plot weak learner boundary with weights
    plot_weak_learner_boundary_and_weights(X_train, y_train, current_learner, idx,
                                       sample_weights=current_weights)

print("\nAll visualizations completed.")

"""# Analysis of AdaBoost Performance #

1. How many base classifiers are needed to achieve 100% classification accuracy on the training set ($n$)?

    

> $100.00\%$ training accuracy was achieved at Iteration 79. Hence, the number of base classifiers need are 79.



2. What is the maximum accuracy achievable on the testing set?



> By inspecting the highest point on the plot, the curve's highest peak appears to be around an accuracy of $0.97$ (or $97\%$) on the y-axis.The final recorded accuracy in your log (with $n=79$) was $97.33\%$.The maximum accuracy is the peak value achieved across all 80 iterations. Observing the plot, the maximum value is slightly above $0.97$ and before the final point, suggesting it's around $97.3\%$ to $97.5\%$.



3. Can the testing set get to 100% classification accuracy?


> No, the maximum achieved is well below $1.0$ (or $100\%$). The recorded accurarcy was $97.33\%$.



4. How many weak learners give maximum accuracy on the testing set ($n_{test}$)?
    
> To find $n_{test}$, we look for the first instance where the testing accuracy curve reaches its highest stable value (the peak) on the x-axis.The accuracy is highly volatile up to about 50 learners.It settles into a high-accuracy plateau around the 53rd learner.The absolute peak seems to occur between 50 and 60 learners, where the line first touches its maximum height. By visually estimating the x-coordinate of the highest spike: the maximum accuracy is likely reached between $t=\mathbf{50}$ and $t=\mathbf{60}$.A conservative and defensible estimate based on the visual peak would be $n_{test} \approx \mathbf{53}$ learners, as this marks the beginning of the plateau where optimal generalization is achieved before the model becomes heavily overfit to the training set (which still requires $n=79$ to fully fit).
"""

